import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LoginForm from '../components/login-form/login-form.component'
import Navbar from '../components/navbar/navbar.component'
import ProductList from '../components/product-list/product-list.component'

export default function Login() {
  return (
    <>
      <Head>
        <title>vending-machine</title>
        <meta name="description" content="half-generated by AI" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar></Navbar>
        <LoginForm></LoginForm>
      </main>
    </>
  )
}
